language: ruby
bundler_args: --without debug extra
before_install:
  - gem install bundler
script: bundle exec rake test_with_coveralls
rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-19mode
  - rbx-2
notifications:
  email:
    - sylvester@keil.or.at
  on_success: change
  on_failure: always
